######Importing tensorflow library

In [1]:
#importing tensorflow
import tensorflow as tf

In [2]:
x = tf.ones([3,2],dtype = tf.float64 )
x

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]])>

In [3]:
y = tf.zeros([3], dtype = tf.int16)
print(y)

tf.Tensor([0 0 0], shape=(3,), dtype=int16)


In [4]:
s = tf.eye(5)
print(s)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


In [5]:
q = tf.random.uniform([5,5])
print(q)

tf.Tensor(
[[0.99261343 0.93842435 0.84120464 0.6557765  0.54165685]
 [0.2126081  0.37039256 0.86575425 0.5354928  0.884617  ]
 [0.5999751  0.46565652 0.82327354 0.5475472  0.24273217]
 [0.05392742 0.24925554 0.25041127 0.09684277 0.25756693]
 [0.6177716  0.09894621 0.353925   0.66660047 0.6087209 ]], shape=(5, 5), dtype=float32)


In [6]:
r = tf.random.normal([4,4])
r

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-0.65309495, -0.14025876,  0.14967969, -1.3704379 ],
       [ 0.6930686 ,  0.14364034,  0.4477268 , -0.74811506],
       [ 1.1295495 , -0.52970856,  0.4045377 , -0.7501527 ],
       [-1.1461151 , -1.4328878 , -0.28606895,  0.9200151 ]],
      dtype=float32)>

In [7]:
e = tf.range(start = 50, limit = 100, delta =5)
e

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95], dtype=int32)>

In [10]:
# concatination by columns
A = tf.constant([[2,4], [5,6]])
B = tf.constant([[3,3], [10,9]])
AB_concat = tf.concat(values = [A,B], axis = 1)
AB_concat


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  3],
       [10,  9]], dtype=int32)>

In [11]:
#concatinating by rows
AB1_concat = tf.concat(values =[A,B], axis = 0)
AB1_concat

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 2,  4],
       [ 5,  6],
       [ 3,  3],
       [10,  9]], dtype=int32)>

###Mathematical operations

In [13]:
#matrix multiplication
c = tf.Variable([[1,2],[2,4]])
d = tf.Variable([[1],[4]])
cd_mul = tf.matmul(c,d)
cd_mul

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 9],
       [18]], dtype=int32)>

In [14]:
#subtraction
x = tf.constant([[45,99,38], [31,29,54]])
y = tf.constant([[11,24,45], [23,39,31]])
z = tf.subtract(x, y)
z

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 34,  75,  -7],
       [  8, -10,  23]], dtype=int32)>

In [16]:
#addition
u = tf.add(x,y)
u

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 56, 123,  83],
       [ 54,  68,  85]], dtype=int32)>

In [17]:
#division
d = tf.divide(x,y)
d

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[4.09090909, 4.125     , 0.84444444],
       [1.34782609, 0.74358974, 1.74193548]])>

In [18]:
#normal multiplication
q = tf.multiply(x,y)
q

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 495, 2376, 1710],
       [ 713, 1131, 1674]], dtype=int32)>

In [23]:
#reduced sum on rows
s = tf.reduce_sum(x*y, axis = 0)
s

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1208, 3507, 3384], dtype=int32)>

In [24]:
#reduced sum on columns
s = tf.reduce_sum(x*y, axis = 1)
s

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4581, 3518], dtype=int32)>

###Advanced operations

In [26]:
#indexing  in tensors
x = tf.constant([1,2,3,4,5,6,7,8,9,11,12,23])
print(x[::])

tf.Tensor([ 1  2  3  4  5  6  7  8  9 11 12 23], shape=(12,), dtype=int32)


In [27]:
print(x[1:])

tf.Tensor([ 2  3  4  5  6  7  8  9 11 12 23], shape=(11,), dtype=int32)


In [28]:
print(x[1:6])

tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int32)


In [29]:
print(x[::-1])

tf.Tensor([23 12 11  9  8  7  6  5  4  3  2  1], shape=(12,), dtype=int32)


In [30]:
print(x[::2])

tf.Tensor([ 1  3  5  7  9 12], shape=(6,), dtype=int32)


In [32]:
#reshaping tensors
y = tf.reshape(x,[3,4])
y

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 11, 12, 23]], dtype=int32)>

In [33]:
#gradient in  tensorflow
x = tf.constant(3.0)
with tf.GradientTape() as g:
  g.watch(x)
  y =  x*x*x
  dy_dx = g.gradient(y,x)
  print(dy_dx)

tf.Tensor(27.0, shape=(), dtype=float32)


In [35]:
#nested gradient
x = tf.constant(6.0)
with tf.GradientTape() as w:
  w.watch(x)
  with tf.GradientTape() as f:
    f.watch(x)
    y = x*x
    dy_dx = f.gradient(y,x)
    d2y_d2x = w.gradient(y,x)
    print(dy_dx)
    print(d2y_d2x)

tf.Tensor(12.0, shape=(), dtype=float32)
tf.Tensor(12.0, shape=(), dtype=float32)


###reshaping images

In [39]:
#generating grayscale images
gray = tf.random.uniform([3,4], maxval = 255, dtype = tf.int64)
gray

<tf.Tensor: shape=(3, 4), dtype=int64, numpy=
array([[ 69, 127, 141, 153],
       [199, 118, 119,  61],
       [199, 129, 166,  27]])>

In [41]:
#reshaping 
gray = tf.reshape(gray,[6+6,1])
gray

<tf.Tensor: shape=(12, 1), dtype=int64, numpy=
array([[ 69],
       [127],
       [141],
       [153],
       [199],
       [118],
       [119],
       [ 61],
       [199],
       [129],
       [166],
       [ 27]])>